// react_consume_api/Components/React_API.js
import React, { useEffect, useState } from 'react';
import { useNavigate } from 'react-router-dom';

function API() {
  const [data, setData] = useState([]);
  const navigate=useNavigate();

  useEffect(() => {
    fetch("http://localhost:3003/getall")
      .then((res) => res.json())
      .then((res) => setData(res));
  }, []);

  const FormatedData = data.map((temp) => {
    return (
      <div class="card col-md-3 mb-4">
        <img src={temp.Image} class="card-img-top" 
          alt="..."/>
        <div class="card-body">
          <h4 class="cars-text">Name: {temp.Name}</h4>
          <h4 class="card-text">TransactionID: {temp.TransactionID}</h4>
          <h4 class="card-text">AccountID: {temp.AccountID}</h4>

          <button class="btn btn-outline-primary m-2" onClick={()=>{
            navigate("../getbyid/" + temp.TransactionID);
          }}>View more</button> 

          <button class="btn btn-outline-danger m-2" onClick={()=>{
            fetch("http://localhost:3003/delete/" + temp.TransactionID,
            {
              method:"DELETE"
            })
            .then(()=>{
              window.location.reload()
            })
          }}>Delete</button>
        </div>
      </div>
    );
  });

  return (
    <div>
      <button
        class="btn btn-outline-secondary m-3"
        onClick={() => {
          navigate("/insert");
        }}
      >
        Add
      </button>
      <div className="row m-2 p-2">{FormatedData}</div>
    </div>
  );
}

export default API;

// angular_consume_api/app/angular-api/angular-api.component.ts
import { Component } from '@angular/core';
import { AngularConsumeAPIService } from '../angular-consume-api.service';
import { Bank } from './bank';

@Component({
  selector: 'app-angular-api',
  templateUrl: './angular-api.component.html',
  styleUrl: './angular-api.component.css'
})
export class AngularAPIComponent {
  data:Bank[]=[];
  constructor(private __api:AngularConsumeAPIService){}

  ngOnInit(){
    /*var result1 = this.api.getallfacultys();
    console.log("before write subscribe getallfacultys result:- ",result1); //return Observable  */
    var result2 = this.__api.getall().subscribe((res:any)=>{
      console.log("res:-",res);
      this.data = res;
      console.log(this.data);
    });
    console.log("after write subscribe getallfacultys result:- ",result2);
  }

  delete(id:any){
    this.__api.delete(id).subscribe((res)=>{
      this.ngOnInit();
    });
  }
}

<button class="btn btn-outline-secondary m-3" routerLink="/insert">Add</button>

<div class="row">
  <div class="col-3  mb-4" *ngFor="let temp of data">
    <div class="card">
      <img
        class="card-img-top"
        [src]="temp.Image"
        alt="Card image cap"
      />
      <div class="card-body">
        <h5 class="card-title">{{"Name:- "+temp.Name }}</h5>
        <h5 class="card-text">{{"TransactionID:- "+temp.TransactionID }}</h5>
        <h5 class="card-text">{{"AccountID:- "+temp.AccountID }}</h5>
        <button class="btn btn-outline-primary" style="margin-right: 10px;" routerLink="/getbyid/{{temp.TransactionID}}">View more</button>        
        <button class="btn btn-outline-danger" (click)="delete(temp.TransactionID)">Delete</button>
      </div>
    </div>
  </div>
</div>
