// angular_consume_api/app/add/add.component.ts
import { Component } from '@angular/core';
import { AngularConsumeAPIService } from '../angular-consume-api.service';
import { Router } from '@angular/router';
import { FormControl, FormGroup } from '@angular/forms';

@Component({
  selector: 'app-add',
  templateUrl: './add.component.html',
  styleUrl: './add.component.css'
})
export class AddComponent {

  constructor(private __api:AngularConsumeAPIService,private __router:Router){}

  myForm = new FormGroup({
    Name : new FormControl(),
    Image : new FormControl(),
    TransactionID : new FormControl(),
    AccountID : new FormControl(),
    TransactionType : new FormControl(),
    Amount : new FormControl(),
    Date : new FormControl(),
  });

  add(){
    console.log("this.myForm.value:- ",this.myForm.value);
    this.__api.insert(this.myForm.value).subscribe((res)=>{
      this.__router.navigate(['getall']);
    });
  }
}

<form [formGroup]="myForm">
    <div class="form-group row">
      <label class="col-sm-2 col-form-label mb-3">Name:</label>
      <div class="col-sm-10">
        <input type="text" class="form-control" placeholder="Name" formControlName="Name"/>
      </div>
  
      <label class="col-sm-2 col-form-label mb-3">Image:</label>
      <div class="col-sm-10">
        <input type="text" class="form-control" placeholder="Image" formControlName="Image"/>
      </div>
  
      <label class="col-sm-2 col-form-label mb-3">TransactionID:</label>
      <div class="col-sm-10">
        <input type="text" class="form-control" placeholder="TransactionID" formControlName="TransactionID"/>
      </div>
  
      <label class="col-sm-2 col-form-label mb-3">AccountID:</label>
      <div class="col-sm-10">
        <input type="text" class="form-control" placeholder="AccountID" formControlName="AccountID"/>
      </div>
  
      <label class="col-sm-2 col-form-label mb-3">TransactionType:</label>
      <div class="col-sm-10">
        <input type="text" class="form-control" placeholder="TransactionType" formControlName="TransactionType"/>
      </div>

      <label class="col-sm-2 col-form-label mb-3">Amount:</label>
      <div class="col-sm-10">
        <input type="text" class="form-control" placeholder="Amount" formControlName="Amount"/>
      </div>

      <label class="col-sm-2 col-form-label mb-3">Date:</label>
      <div class="col-sm-10">
        <input type="text" class="form-control" placeholder="Date" formControlName="Date"/>
      </div>
  
      <div class="col-sm-12 text-center">
        <button class="btn btn-outline-secondary" type="button" (click)="add()">Add</button>
      </div>
  
    </div>
  </form>

// react_consume_api/Components/Add.js
import { useState } from "react";
import { useNavigate} from "react-router-dom";

function Add() {
  const navigate=useNavigate();
  const [data,setData]=useState({});

  return (
    <>
    <table class="table table-striped">
    <tbody>
    <tr>
        <td>Enter Name:</td>
        <td>
            <input 
                value={data.Name}
                onChange={(e)=>{
                setData({...data,Name:e.target.value});
            }} type="text" />
        </td>
    </tr>

    <tr>
        <td>Enter Image:</td>
        <td>
            <input 
                value={data.Image}
                onChange={(e)=>{
                setData({...data,Image:e.target.value});
            }} type="text" />   
        </td>
    </tr>

    <tr>
        <td>Enter TransactionID:</td>
        <td>
            <input 
                value={data.TransactionID}
                onChange={(e)=>{
                setData({...data,TransactionID:e.target.value});
            }} type="text" />
        </td>
    </tr>
        
    <tr>
        <td>Enter AccountID:</td>
        <td>
            <input 
                value={data.AccountID}
                onChange={(e)=>{
                setData({...data,AccountID:e.target.value});
            }} type="text" />
        </td>
    </tr>

    <tr>
        <td>Enter TransactionType:</td>
        <td>
            <input 
                value={data.TransactionType}
                onChange={(e)=>{
                setData({...data,TransactionType:e.target.value});
            }} type="text" />
        </td>
    </tr>

    <tr>
        <td>Enter Amount:</td>
        <td>
            <input 
                value={data.Amount}
                onChange={(e)=>{
                setData({...data,Amount:e.target.value});
            }} type="text" />
        </td>
    </tr>

    <tr>
        <td>Enter Date:</td>
        <td>
            <input 
                value={data.Date}
                onChange={(e)=>{
                setData({...data,Date:e.target.value});
            }} type="text" />
        </td>
    </tr>
    </tbody>
    </table>

    <div style={{ textAlign: 'center' }}>
      <button className="btn btn-outline-secondary" onClick={()=>{
        //console.log(data);
        fetch("http://localhost:3003/insert",
        {
            method:"POST",
            body:JSON.stringify(data),
            headers:{
                "Content-type":"application/json"
            }
        })
        .then(()=>{navigate("/getall")});
      }}>
        Add
      </button>
    </div>
    </>
  );
}
export default Add;
