// angular_consume_api/app/bank-details/bank-details.component.ts
import { Component } from '@angular/core';
import { AngularConsumeAPIService } from '../angular-consume-api.service';
import { ActivatedRoute, Router } from '@angular/router';
import { Bank } from '../angular-api/bank';

@Component({
  selector: 'app-bank-details',
  templateUrl: './bank-details.component.html',
  styleUrl: './bank-details.component.css'
})
export class BankDetailsComponent {
  id=0;
  data:Bank = new Bank();
  constructor(private __api:AngularConsumeAPIService,private __actroute:ActivatedRoute,private __router:Router){}
  ngOnInit(){
    console.log("this.__actroute.snapshot.params",this.__actroute);
    this.id=this.__actroute.snapshot.params['id'];
    this.__api.getbyid(this.id).subscribe((res:any)=>{
      this.data = res;
    });
  }

  delete(id:any){
    this.__api.delete(this.id).subscribe((res:any)=>{
      this.__router.navigate(['/getall']);
    });
  }
}

<table class="table table-bordered">
    <thead>
      <tr>
        <th scope="col">Name</th>
        <th scope="col">Image</th>
        <th scope="col">TransactionID</th>
        <th scope="col">AccountID</th>
        <th scope="col">TransactionType</th>
        <th scope="col">Amount</th>
        <th scope="col">Date</th>
      </tr>
    </thead>
    <tbody>
      <tr>
        <td>{{ data.Name }}</td>
        <td>{{ data.Image }}</td>
        <td>{{ data.TransactionID }}</td>
        <td>{{ data.AccountID }}</td>
        <td>{{ data.TransactionType }}</td>
        <td>{{ data.Amount }}</td>
        <td>{{ data.Date }}</td>
      </tr>
      <tr></tr>
    </tbody>
  </table>
  
  <div class="text-center">
      <button class="btn btn-outline-primary" style="margin-right: 10px;" routerLink="/getall">Back</button>
      <button class="btn btn-outline-warning" style="margin-right: 10px;" routerLink="/update/{{data.TransactionID}}">Edit</button>
      <button class="btn btn-outline-danger" (click)="delete(data.TransactionID)">Delete</button>
  </div>

// react_consume_api/Components/Bank_Details.js
import { useEffect, useState } from "react";
import { useNavigate, useParams} from "react-router-dom";

function Bank_Detail() {
  let params=useParams();
  const navigate=useNavigate();
  const [data, setData] = useState({});
  useEffect(() => {
    fetch("http://localhost:3003/getbyid/" + params.id, {
      method: "GET",
    })
      .then((res) => {
        return res.json();
      })
      .then((res) => {
        setData(res);
      });
  }, []);
  return (
    <>
      <div class="card col-md-3">
        <img src={data.Image} class="card-img-top" alt="..." />
        <div class="card-body">
          <h4 class="card-text">Name: {data.Name}</h4>
          <h4 class="card-text">TransactionID: {data.TransactionID}</h4>
          <h4 class="card-text">AccountID: {data.AccountID}</h4>
          <h4 class="card-text">TransactionType: {data.TransactionType}</h4>
          <h4 class="card-text">Amount: {data.Amount}</h4>
          <h4 class="card-text">Date: {data.Date}</h4>

          <button class="btn btn-outline-success" 
          onClick={() => {
            navigate("/update/"+params.id);
          }}
          >
            Edit
          </button>

          <span style={{ marginRight: "10px" }}></span>

          <button
            class="btn btn-outline-danger"
            onClick={() => {
              fetch("http://localhost:3003/delete/"+params.id,
              {
                  method: "DELETE",
              })
              .then(() => {
                navigate("/getall");
              });
            }}
          >
            Delete
          </button>
        </div>
      </div>
    </>
  );
}
export default Bank_Detail;
